services:
  one-hub:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: one-hub
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
      - ./config.yaml:/data/config.yaml
    depends_on:
      - redis
      - db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:latest
    container_name: redis
    restart: always

  db:
    image: mysql:8.2.0
    restart: always
    container_name: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
    command: ['mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      TZ: Asia/Shanghai
      MYSQL_ROOT_PASSWORD: "OneAPI@justsong"
      MYSQL_USER: oneapi
      MYSQL_PASSWORD: "123456"
      MYSQL_DATABASE: one-api
