version: "3.4"

services:
  one-hub:
    build:
      context: .  # 使用当前目录作为构建上下文
      dockerfile: Dockerfile  # 使用项目中的 Dockerfile
    container_name: one-hub
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data
      # 如果需要热更新，可以添加源代码目录映射
      - .:/app
    environment:
      - SQL_DSN=oneapi:123456@tcp(db:3306)/one-api
      - REDIS_CONN_STRING=redis://redis
      - SESSION_SECRET=random_string
      - USER_TOKEN_SECRET=random_string
      - TZ=Asia/Shanghai
    depends_on:
      - redis
      - db
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget -q -O - http://localhost:3000/api/status | grep -o '\"success\":\\s*true' | awk -F: '{print $2}'",
        ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:latest
    container_name: redis
    restart: always

  db:
    image: mysql:8.2.0
    restart: always
    container_name: mysql
    volumes:
      - ./data/mysql:/var/lib/mysql # 挂载目录，持久化存储
    ports:
      - "3306:3306"
    environment:
      TZ: Asia/Shanghai # 设置时区
      MYSQL_ROOT_PASSWORD: "OneAPI@justsong" # 设置 root 用户的密码
      MYSQL_USER: oneapi # 创建专用用户
      MYSQL_PASSWORD: "123456" # 设置专用用户密码
      MYSQL_DATABASE: one-api # 自动创建数据库
